// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFk0okMoBJo5v3dsckoB24pi4mUfE-OMU',
    appId: '1:522043114149:web:7d71e146cb99398728834c',
    messagingSenderId: '522043114149',
    projectId: 'gmr-app-626ff',
    authDomain: 'gmr-app-626ff.firebaseapp.com',
    storageBucket: 'gmr-app-626ff.firebasestorage.app',
    measurementId: 'G-NDPLSZTF4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC--4vYq8gVZiSVHexLPLuGu7SYYzKhYfU',
    appId: '1:522043114149:android:810e68fe6aeb928b28834c',
    messagingSenderId: '522043114149',
    projectId: 'gmr-app-626ff',
    storageBucket: 'gmr-app-626ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5q_0kIRdJfhnnjwBkV7wYYgnOODCDiYU',
    appId: '1:522043114149:ios:c175b09e6d2a318728834c',
    messagingSenderId: '522043114149',
    projectId: 'gmr-app-626ff',
    storageBucket: 'gmr-app-626ff.firebasestorage.app',
    iosBundleId: 'com.example.getMyRefund',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5q_0kIRdJfhnnjwBkV7wYYgnOODCDiYU',
    appId: '1:522043114149:ios:c175b09e6d2a318728834c',
    messagingSenderId: '522043114149',
    projectId: 'gmr-app-626ff',
    storageBucket: 'gmr-app-626ff.firebasestorage.app',
    iosBundleId: 'com.example.getMyRefund',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFk0okMoBJo5v3dsckoB24pi4mUfE-OMU',
    appId: '1:522043114149:web:60e6d8d587d9997228834c',
    messagingSenderId: '522043114149',
    projectId: 'gmr-app-626ff',
    authDomain: 'gmr-app-626ff.firebaseapp.com',
    storageBucket: 'gmr-app-626ff.firebasestorage.app',
    measurementId: 'G-NQ3DF6FYKJ',
  );

}