// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHyivOqPNgwKjTrTcI2Q-bVyOTFmDWXSU',
    appId: '1:506405305747:web:ba71afce7c670f210f3c66',
    messagingSenderId: '506405305747',
    projectId: 'get-my-refund-e9c86',
    authDomain: 'get-my-refund-e9c86.firebaseapp.com',
    storageBucket: 'get-my-refund-e9c86.firebasestorage.app',
    measurementId: 'G-2KPC2EC4KZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgzGfGIVUAAoKA8NVYC7cKaQbN9KTZWW4',
    appId: '1:506405305747:android:25a3af16f04036ff0f3c66',
    messagingSenderId: '506405305747',
    projectId: 'get-my-refund-e9c86',
    storageBucket: 'get-my-refund-e9c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6tp0jPQXwiJ8yC9NEKBJvbPCNTRdmnOI',
    appId: '1:506405305747:ios:865e74f23d811ea10f3c66',
    messagingSenderId: '506405305747',
    projectId: 'get-my-refund-e9c86',
    storageBucket: 'get-my-refund-e9c86.firebasestorage.app',
    iosBundleId: 'com.example.getMyRefund',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6tp0jPQXwiJ8yC9NEKBJvbPCNTRdmnOI',
    appId: '1:506405305747:ios:865e74f23d811ea10f3c66',
    messagingSenderId: '506405305747',
    projectId: 'get-my-refund-e9c86',
    storageBucket: 'get-my-refund-e9c86.firebasestorage.app',
    iosBundleId: 'com.example.getMyRefund',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHyivOqPNgwKjTrTcI2Q-bVyOTFmDWXSU',
    appId: '1:506405305747:web:f9fd331f33065da00f3c66',
    messagingSenderId: '506405305747',
    projectId: 'get-my-refund-e9c86',
    authDomain: 'get-my-refund-e9c86.firebaseapp.com',
    storageBucket: 'get-my-refund-e9c86.firebasestorage.app',
    measurementId: 'G-K48PKNCBBG',
  );
}
