// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4CssgKeRlgoPLwr_FbUnUUFKHwjy_L0w',
    appId: '1:512066556824:web:2aa058dc790d5befc411ed',
    messagingSenderId: '512066556824',
    projectId: 'get-my-refund-5096f',
    authDomain: 'get-my-refund-5096f.firebaseapp.com',
    storageBucket: 'get-my-refund-5096f.firebasestorage.app',
    measurementId: 'G-DQQMSXG5YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHLPAUiF0o_WarQzKk9j6W74z3-JfBvlc',
    appId: '1:512066556824:android:69b108eb7d9e6fc7c411ed',
    messagingSenderId: '512066556824',
    projectId: 'get-my-refund-5096f',
    storageBucket: 'get-my-refund-5096f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4bfC8kzed4kJ7MoBHisIT75bGjZzQP9M',
    appId: '1:512066556824:ios:92ecad3c210506fcc411ed',
    messagingSenderId: '512066556824',
    projectId: 'get-my-refund-5096f',
    storageBucket: 'get-my-refund-5096f.firebasestorage.app',
    iosClientId: '512066556824-bojtvrk0cbgnqq0qjlpgdm8lhv7266u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.getMyRefund',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4bfC8kzed4kJ7MoBHisIT75bGjZzQP9M',
    appId: '1:512066556824:ios:92ecad3c210506fcc411ed',
    messagingSenderId: '512066556824',
    projectId: 'get-my-refund-5096f',
    storageBucket: 'get-my-refund-5096f.firebasestorage.app',
    iosClientId: '512066556824-bojtvrk0cbgnqq0qjlpgdm8lhv7266u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.getMyRefund',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4CssgKeRlgoPLwr_FbUnUUFKHwjy_L0w',
    appId: '1:512066556824:web:570d7cfe6c052c98c411ed',
    messagingSenderId: '512066556824',
    projectId: 'get-my-refund-5096f',
    authDomain: 'get-my-refund-5096f.firebaseapp.com',
    storageBucket: 'get-my-refund-5096f.firebasestorage.app',
    measurementId: 'G-0LBLSW6WM6',
  );

}